"use client";
import { useState } from "react";
const services = ["品牌策略", "视觉系统", "数字体验"];
export default function Home() { const [menuOpen,setMenuOpen]=useState(false); return <main>
<nav className="nav shell"><a className="logo" href="#top">NØRMA<span>®</span></a><div className={`nav-links ${menuOpen?"open":""}`}><a href="#work">精选项目</a><a href="#about">关于我们</a><a href="#contact">联系</a></div><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="打开菜单">{menuOpen?"×":"菜单"}</button></nav>
<section className="hero shell" id="top"><div className="eyebrow"><span className="dot" /> 独立创意工作室 · 上海 / 全球</div><h1>让品牌<br/><em>更有分量。</em></h1><div className="hero-bottom"><p>我们用清晰的策略、克制的设计和有温度的数字体验，帮助新一代品牌被看见、被记住。</p><a className="circle-arrow" href="#work" aria-label="查看项目">↘</a></div></section>
<section className="marquee"><div>STRATEGY · IDENTITY · DIGITAL · MOTION · STRATEGY · IDENTITY · DIGITAL · MOTION · </div></section>
<section className="work shell" id="work"><div className="section-label">01 / 精选项目</div><div className="project-grid"><article className="project project-dark"><div className="project-mark">AURA<br/><small>FORM / FUNCTION / FEELING</small></div><div className="project-meta"><strong>AURA HOUSE</strong><span>品牌策略 · 2024</span></div></article><article className="project project-orange"><div className="orb">N</div><div className="project-meta"><strong>NOMAD OBJECTS</strong><span>视觉系统 · 2023</span></div></article><article className="project project-cream"><div className="serif-word">mizu</div><div className="project-meta"><strong>MIZU TEA</strong><span>数字体验 · 2024</span></div></article></div></section>
<section className="about shell" id="about"><div className="section-label">02 / 我们做什么</div><div className="about-content"><h2>少一点噪音，<br/><span>多一点意义。</span></h2><div>{services.map((s,i)=><div className="service" key={s}><span>0{i+1}</span><b>{s}</b><i>↗</i></div>)}</div></div></section>
<footer className="footer shell" id="contact"><div className="footer-title">有个想法？<br/><a href="mailto:hello@norma.studio">和我们聊聊 ↗</a></div><div className="footer-bottom"><span>© 2024 NØRMA STUDIO</span><span>Instagram · Xiaohongshu</span><span>上海 · 中国</span></div></footer></main> }
